// pool manager abi

export const poolManagerAbi: any[] = [
  { stateMutability: 'Nonpayable', type: 'Constructor' },
  { name: 'AppUnregistered', type: 'Error' },
  { name: 'CannotUpdateEmptyPosition', type: 'Error' },
  {
    inputs: [
      { name: 'currency0', type: 'address' },
      { name: 'currency1', type: 'address' },
    ],
    name: 'CurrenciesInitializedOutOfOrder',
    type: 'Error',
  },
  { name: 'CurrencyNotSettled', type: 'Error' },
  { name: 'DelegateCallNotAllowed', type: 'Error' },
  { name: 'FeeCurrencySynced', type: 'Error' },
  { name: 'HookConfigValidationError', type: 'Error' },
  { name: 'HookDeltaExceedsSwapAmount', type: 'Error' },
  { name: 'HookPermissionsValidationError', type: 'Error' },
  { name: 'InvalidCaller', type: 'Error' },
  { name: 'InvalidFeeForExactOut', type: 'Error' },
  { name: 'InvalidHookResponse', type: 'Error' },
  {
    inputs: [
      { name: 'sqrtPriceCurrentX96', type: 'uint160' },
      { name: 'sqrtPriceLimitX96', type: 'uint160' },
    ],
    name: 'InvalidSqrtPriceLimit',
    type: 'Error',
  },
  { inputs: [{ name: 'sqrtPriceX96', type: 'uint160' }], name: 'InvalidSqrtRatio', type: 'Error' },
  { inputs: [{ name: 'tick', type: 'int24' }], name: 'InvalidTick', type: 'Error' },
  { inputs: [{ name: 'fee', type: 'uint24' }], name: 'LPFeeTooLarge', type: 'Error' },
  { inputs: [{ name: 'locker', type: 'address' }], name: 'LockerAlreadySet', type: 'Error' },
  { name: 'MustClearExactPositiveDelta', type: 'Error' },
  { name: 'NoLiquidityToReceiveFees', type: 'Error' },
  { name: 'NoLocker', type: 'Error' },
  { name: 'PoolAlreadyInitialized', type: 'Error' },
  { name: 'PoolManagerMismatch', type: 'Error' },
  { name: 'PoolNotInitialized', type: 'Error' },
  { name: 'PoolPaused', type: 'Error' },
  { name: 'ProtocolFeeCannotBeFetched', type: 'Error' },
  { inputs: [{ name: 'fee', type: 'uint24' }], name: 'ProtocolFeeTooLarge', type: 'Error' },
  { name: 'SettleNonNativeCurrencyWithValue', type: 'Error' },
  { name: 'SwapAmountCannotBeZero', type: 'Error' },
  { inputs: [{ name: 'tick', type: 'int24' }], name: 'TickLiquidityOverflow', type: 'Error' },
  { inputs: [{ name: 'tickLower', type: 'int24' }], name: 'TickLowerOutOfBounds', type: 'Error' },
  { inputs: [{ name: 'tickSpacing', type: 'int24' }], name: 'TickSpacingTooLarge', type: 'Error' },
  { inputs: [{ name: 'tickSpacing', type: 'int24' }], name: 'TickSpacingTooSmall', type: 'Error' },
  { inputs: [{ name: 'tickUpper', type: 'int24' }], name: 'TickUpperOutOfBounds', type: 'Error' },
  {
    inputs: [
      { name: 'tickLower', type: 'int24' },
      { name: 'tickUpper', type: 'int24' },
    ],
    name: 'TicksMisordered',
    type: 'Error',
  },
  { name: 'UnauthorizedDynamicLPFeeUpdate', type: 'Error' },
  { name: 'UnusedBitsNonZero', type: 'Error' },
  { inputs: [{ indexed: true, name: 'app', type: 'address' }], name: 'AppRegistered', type: 'Event' },
  {
    inputs: [
      { indexed: true, name: 'owner', type: 'address' },
      { indexed: true, name: 'spender', type: 'address' },
      { indexed: true, name: 'currency', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    name: 'Approval',
    type: 'Event',
  },
  {
    inputs: [
      { indexed: true, name: 'id', type: 'bytes32' },
      { indexed: true, name: 'sender', type: 'address' },
      { name: 'amount0', type: 'uint256' },
      { name: 'amount1', type: 'uint256' },
      { name: 'tick', type: 'int24' },
    ],
    name: 'Donate',
    type: 'Event',
  },
  {
    inputs: [
      { indexed: true, name: 'id', type: 'bytes32' },
      { name: 'dynamicLPFee', type: 'uint24' },
    ],
    name: 'DynamicLPFeeUpdated',
    type: 'Event',
  },
  {
    inputs: [
      { indexed: true, name: 'id', type: 'bytes32' },
      { indexed: true, name: 'currency0', type: 'address' },
      { indexed: true, name: 'currency1', type: 'address' },
      { name: 'hooks', type: 'address' },
      { name: 'fee', type: 'uint24' },
      { name: 'parameters', type: 'bytes32' },
      { name: 'sqrtPriceX96', type: 'uint160' },
      { name: 'tick', type: 'int24' },
      { name: 'poolCount', type: 'uint256' },
    ],
    name: 'Initialize',
    type: 'Event',
  },
  {
    inputs: [
      { indexed: true, name: 'id', type: 'bytes32' },
      { indexed: true, name: 'sender', type: 'address' },
      { name: 'tickLower', type: 'int24' },
      { name: 'tickUpper', type: 'int24' },
      { name: 'liquidityDelta', type: 'int256' },
      { name: 'salt', type: 'bytes32' },
    ],
    name: 'ModifyLiquidity',
    type: 'Event',
  },
  {
    inputs: [
      { indexed: true, name: 'owner', type: 'address' },
      { indexed: true, name: 'operator', type: 'address' },
      { name: 'approved', type: 'bool' },
    ],
    name: 'OperatorSet',
    type: 'Event',
  },
  {
    inputs: [
      { indexed: true, name: 'previousOwner', type: 'address' },
      { indexed: true, name: 'newOwner', type: 'address' },
    ],
    name: 'OwnershipTransferred',
    type: 'Event',
  },
  {
    inputs: [{ indexed: true, name: 'protocolFeeController', type: 'address' }],
    name: 'ProtocolFeeControllerUpdated',
    type: 'Event',
  },
  {
    inputs: [
      { indexed: true, name: 'id', type: 'bytes32' },
      { name: 'protocolFee', type: 'uint24' },
    ],
    name: 'ProtocolFeeUpdated',
    type: 'Event',
  },
  {
    inputs: [
      { indexed: true, name: 'id', type: 'bytes32' },
      { indexed: true, name: 'sender', type: 'address' },
      { name: 'amount0', type: 'int128' },
      { name: 'amount1', type: 'int128' },
      { name: 'sqrtPriceX96', type: 'uint160' },
      { name: 'liquidity', type: 'uint128' },
      { name: 'tick', type: 'int24' },
      { name: 'fee', type: 'uint24' },
      { name: 'protocolFee', type: 'uint16' },
    ],
    name: 'Swap',
    type: 'Event',
  },
  {
    inputs: [
      { name: 'caller', type: 'address' },
      { indexed: true, name: 'from', type: 'address' },
      { indexed: true, name: 'to', type: 'address' },
      { indexed: true, name: 'currency', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    name: 'Transfer',
    type: 'Event',
  },
  {
    outputs: [{ name: 'amount', type: 'uint256' }],
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'spender', type: 'address' },
      { name: 'currency', type: 'address' },
    ],
    name: 'allowance',
    stateMutability: 'View',
    type: 'Function',
  },
  {
    outputs: [{ type: 'bool' }],
    inputs: [
      { name: 'spender', type: 'address' },
      { name: 'currency', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    name: 'approve',
    stateMutability: 'Nonpayable',
    type: 'Function',
  },
  {
    outputs: [{ name: 'balance', type: 'uint256' }],
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'currency', type: 'address' },
    ],
    name: 'balanceOf',
    stateMutability: 'View',
    type: 'Function',
  },
  {
    inputs: [
      { name: 'from', type: 'address' },
      { name: 'currency', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    name: 'burn',
    stateMutability: 'Nonpayable',
    type: 'Function',
  },
  {
    inputs: [
      { name: 'currency', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    name: 'clear',
    stateMutability: 'Nonpayable',
    type: 'Function',
  },
  {
    inputs: [
      { name: 'currency', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'recipient', type: 'address' },
    ],
    name: 'collectFee',
    stateMutability: 'Nonpayable',
    type: 'Function',
  },
  {
    outputs: [{ name: 'amountCollected', type: 'uint256' }],
    inputs: [
      { name: 'recipient', type: 'address' },
      { name: 'currency', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    name: 'collectProtocolFees',
    stateMutability: 'Nonpayable',
    type: 'Function',
  },
  {
    outputs: [{ type: 'int256' }],
    inputs: [
      { name: 'settler', type: 'address' },
      { name: 'currency', type: 'address' },
    ],
    name: 'currencyDelta',
    stateMutability: 'View',
    type: 'Function',
  },
  {
    outputs: [{ name: 'delta', type: 'int256' }],
    inputs: [
      { name: 'key', type: 'tuple' },
      { name: 'amount0', type: 'uint256' },
      { name: 'amount1', type: 'uint256' },
      { name: 'hookData', type: 'bytes' },
    ],
    name: 'donate',
    stateMutability: 'Nonpayable',
    type: 'Function',
  },
  {
    outputs: [{ type: 'bytes32' }],
    inputs: [{ name: 'slot', type: 'bytes32' }],
    name: 'extsload',
    stateMutability: 'View',
    type: 'Function',
  },
  {
    outputs: [{ type: 'bytes32[]' }],
    inputs: [{ name: 'slots', type: 'bytes32[]' }],
    name: 'extsload',
    stateMutability: 'View',
    type: 'Function',
  },
  {
    outputs: [
      { name: 'feeGrowthGlobal0x128', type: 'uint256' },
      { name: 'feeGrowthGlobal1x128', type: 'uint256' },
    ],
    inputs: [{ name: 'id', type: 'bytes32' }],
    name: 'getFeeGrowthGlobals',
    stateMutability: 'View',
    type: 'Function',
  },
  {
    outputs: [{ name: 'liquidity', type: 'uint128' }],
    inputs: [
      { name: 'id', type: 'bytes32' },
      { name: '_owner', type: 'address' },
      { name: 'tickLower', type: 'int24' },
      { name: 'tickUpper', type: 'int24' },
      { name: 'salt', type: 'bytes32' },
    ],
    name: 'getLiquidity',
    stateMutability: 'View',
    type: 'Function',
  },
  {
    outputs: [{ name: 'liquidity', type: 'uint128' }],
    inputs: [{ name: 'id', type: 'bytes32' }],
    name: 'getLiquidity',
    stateMutability: 'View',
    type: 'Function',
  },
  { outputs: [{ type: 'address' }], name: 'getLocker', stateMutability: 'View', type: 'Function' },
  {
    outputs: [{ name: 'tickBitmap', type: 'uint256' }],
    inputs: [
      { name: 'id', type: 'bytes32' },
      { name: 'word', type: 'int16' },
    ],
    name: 'getPoolBitmapInfo',
    stateMutability: 'View',
    type: 'Function',
  },
  {
    outputs: [{ type: 'tuple' }],
    inputs: [
      { name: 'id', type: 'bytes32' },
      { name: 'tick', type: 'int24' },
    ],
    name: 'getPoolTickInfo',
    stateMutability: 'View',
    type: 'Function',
  },
  {
    outputs: [{ name: 'position', type: 'tuple' }],
    inputs: [
      { name: 'id', type: 'bytes32' },
      { name: 'owner', type: 'address' },
      { name: 'tickLower', type: 'int24' },
      { name: 'tickUpper', type: 'int24' },
      { name: 'salt', type: 'bytes32' },
    ],
    name: 'getPosition',
    stateMutability: 'View',
    type: 'Function',
  },
  {
    outputs: [
      { name: 'sqrtPriceX96', type: 'uint160' },
      { name: 'tick', type: 'int24' },
      { name: 'protocolFee', type: 'uint24' },
      { name: 'lpFee', type: 'uint24' },
    ],
    inputs: [{ name: 'id', type: 'bytes32' }],
    name: 'getSlot0',
    stateMutability: 'View',
    type: 'Function',
  },
  { outputs: [{ type: 'uint256' }], name: 'getUnsettledDeltasCount', stateMutability: 'View', type: 'Function' },
  {
    outputs: [{ type: 'address' }, { type: 'uint256' }],
    name: 'getVaultReserve',
    stateMutability: 'View',
    type: 'Function',
  },
  {
    outputs: [{ name: 'tick', type: 'int24' }],
    inputs: [
      { name: 'key', type: 'tuple' },
      { name: 'sqrtPriceX96', type: 'uint160' },
    ],
    name: 'initialize',
    stateMutability: 'Nonpayable',
    type: 'Function',
  },
  {
    outputs: [{ name: 'isOperator', type: 'bool' }],
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'operator', type: 'address' },
    ],
    name: 'isOperator',
    stateMutability: 'View',
    type: 'Function',
  },
  {
    outputs: [{ name: 'result', type: 'bytes' }],
    inputs: [{ name: 'data', type: 'bytes' }],
    name: 'lock',
    stateMutability: 'Nonpayable',
    type: 'Function',
  },
  {
    inputs: [
      { name: 'to', type: 'address' },
      { name: 'currency', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    name: 'mint',
    stateMutability: 'Nonpayable',
    type: 'Function',
  },
  {
    outputs: [
      { name: 'delta', type: 'int256' },
      { name: 'feeDelta', type: 'int256' },
    ],
    inputs: [
      { name: 'key', type: 'tuple' },
      { name: 'params', type: 'tuple' },
      { name: 'hookData', type: 'bytes' },
    ],
    name: 'modifyLiquidity',
    stateMutability: 'Nonpayable',
    type: 'Function',
  },
  { outputs: [{ type: 'address' }], name: 'owner', stateMutability: 'View', type: 'Function' },
  { outputs: [{ type: 'uint256' }], name: 'poolCount', stateMutability: 'View', type: 'Function' },
  {
    outputs: [
      { name: 'currency0', type: 'address' },
      { name: 'currency1', type: 'address' },
      { name: 'hooks', type: 'address' },
      { name: 'poolManager', type: 'address' },
      { name: 'fee', type: 'uint24' },
      { name: 'parameters', type: 'bytes32' },
    ],
    inputs: [{ name: 'id', type: 'bytes32' }],
    name: 'poolIdToPoolKey',
    stateMutability: 'View',
    type: 'Function',
  },
  {
    outputs: [{ type: 'bytes32' }],
    inputs: [{ type: 'uint256' }],
    name: 'poolIndex',
    stateMutability: 'View',
    type: 'Function',
  },
  { outputs: [{ type: 'address' }], name: 'protocolFeeController', stateMutability: 'View', type: 'Function' },
  {
    outputs: [{ name: 'amount', type: 'uint256' }],
    inputs: [{ name: 'currency', type: 'address' }],
    name: 'protocolFeesAccrued',
    stateMutability: 'View',
    type: 'Function',
  },
  {
    outputs: [{ type: 'bool' }],
    inputs: [
      { name: 'operator', type: 'address' },
      { name: 'approved', type: 'bool' },
    ],
    name: 'setOperator',
    stateMutability: 'Nonpayable',
    type: 'Function',
  },
  {
    inputs: [
      { name: 'key', type: 'tuple' },
      { name: 'newProtocolFee', type: 'uint24' },
    ],
    name: 'setProtocolFee',
    stateMutability: 'Nonpayable',
    type: 'Function',
  },
  {
    inputs: [{ name: 'controller', type: 'address' }],
    name: 'setProtocolFeeController',
    stateMutability: 'Nonpayable',
    type: 'Function',
  },
  { outputs: [{ type: 'uint256' }], name: 'settle', stateMutability: 'Payable', type: 'Function' },
  {
    outputs: [{ type: 'uint256' }],
    inputs: [{ name: 'recipient', type: 'address' }],
    name: 'settleFor',
    stateMutability: 'Payable',
    type: 'Function',
  },
  {
    outputs: [{ type: 'bool' }],
    inputs: [{ name: 'interfaceId', type: 'bytes4' }],
    name: 'supportsInterface',
    stateMutability: 'View',
    type: 'Function',
  },
  {
    outputs: [{ name: 'delta', type: 'int256' }],
    inputs: [
      { name: 'key', type: 'tuple' },
      { name: 'params', type: 'tuple' },
      { name: 'hookData', type: 'bytes' },
    ],
    name: 'swap',
    stateMutability: 'Nonpayable',
    type: 'Function',
  },
  { inputs: [{ name: 'currency', type: 'address' }], name: 'sync', stateMutability: 'Nonpayable', type: 'Function' },
  {
    inputs: [
      { name: 'currency', type: 'address' },
      { name: 'to', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    name: 'take',
    stateMutability: 'Nonpayable',
    type: 'Function',
  },
  {
    outputs: [{ type: 'bool' }],
    inputs: [
      { name: 'receiver', type: 'address' },
      { name: 'currency', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    name: 'transfer',
    stateMutability: 'Nonpayable',
    type: 'Function',
  },
  {
    outputs: [{ type: 'bool' }],
    inputs: [
      { name: 'sender', type: 'address' },
      { name: 'receiver', type: 'address' },
      { name: 'currency', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    name: 'transferFrom',
    stateMutability: 'Nonpayable',
    type: 'Function',
  },
  {
    inputs: [{ name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    stateMutability: 'Nonpayable',
    type: 'Function',
  },
  {
    inputs: [
      { name: 'key', type: 'tuple' },
      { name: 'newDynamicLPFee', type: 'uint24' },
    ],
    name: 'updateDynamicLPFee',
    stateMutability: 'Nonpayable',
    type: 'Function',
  },
  { outputs: [{ type: 'address' }], name: 'vault', stateMutability: 'View', type: 'Function' },
]
